{% set name = "voxel51-eta" %}
{% set version = "0.13.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d1f1f67a7ffc70a755e05bb650a9649752a69997a2c78f361b63074518948c34

build:
  noarch: python
  entry_points:
    - eta=eta.core.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - importlib-metadata
    - pip
  run:
    - python >={{ python_min }}
    - argcomplete
    - dill
    - future
    - glob2
    - importlib-metadata
    - jsonlines
    - numpy
    - packaging
    - pillow >=6.2
    - py7zr
    - python-dateutil
    - pytz
    - rarfile
    - requests
    - retrying
    - six
    - scikit-image
    - sortedcontainers
    - tabulate
    - tzlocal
    - urllib3
    - opencv <5,>=4.1

test:
  imports:
    - eta
  commands:
    - pip check
    - eta --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/voxel51/eta
  summary: Extensible Toolkit for Analytics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
