{% set name = "voxel51-eta" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a815d714b6ec6df91e9f16b830aa290ea36a4a9328397dc72e98d3b21b2169bb

build:
  noarch: python
  entry_points:
    - eta=eta.core.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - wheel
    - importlib-metadata
    - pip
  run:
    - python >=3.7
    - argcomplete
    - dill
    - future
    - glob2
    - importlib-metadata
    - jsonlines
    - numpy
    - packaging
    - pillow >=6.2
    - py7zr
    - python-dateutil
    - pytz
    - rarfile
    - requests
    - retrying
    - six
    - scikit-image
    - sortedcontainers
    - tabulate
    - tzlocal
    - urllib3
    - opencv <5,>=4.1

test:
  imports:
    - eta
  commands:
    - pip check
    - eta --help
  requires:
    - pip

about:
  home: https://github.com/voxel51/eta
  summary: Extensible Toolkit for Analytics
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lucasew
